name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - develop # Cambia 'main' si usas otro nombre de rama principal

jobs:
  build-and-deploy:
    name: Build and Deploy Flutter Web
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # Paso 4: Construir para Web
      - name: Build Flutter Web
        run: flutter build web --release

      # Paso 5: Desplegar a Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting
