name: Deploy Flutter Web

on:
  push:
    branches:
      - main # Ejecuta el workflow cuando haya cambios en la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # 3. Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 4. Construir el proyecto para la web
      - name: Build for web
        run: flutter build web

      # 5. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
