name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - develop # Ejecutar al hacer push a la rama main

jobs:
  build-and-deploy:
    name: Build and Deploy Flutter Web
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0" # Usa la última versión estable

      # 3. Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 4. Construir el proyecto Flutter para Web
      - name: Build Flutter Web
        run: flutter build web --release

      # 5. Desplegar a Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting
